### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by sjfloat** [chengpohi/ammonite-vi#2]
`not found: https://repo1.maven.org/maven2/com/github/chengpohi/ammonite-vi_2.13/1.6.1/ammonite-vi_2.13-1.6.1.pom`

**Comment by chengpohi** [comment]
Hi @sjfloat , it's sorry for reply late, I will check this issue now :)

**Comment by robbyki** [comment]
any update on this? also getting this when trying against 2.12. 
```
predef.sc:13: type mismatch;
 found   : ammonite.repl.FullReplAPI
 required: ammonite.repl.ReplAPI
    com.github.chengpohi.VIMode(repl, wd)
                               ^
Compilation Failed
```

**Comment by chengpohi** [comment]
@robbyki @sjfloat  I have updated the plugin, but for now this version is compatible with Scala 2.13 and Ammonite 2.X.

```
interp.load.ivy("com.github.chengpohi" %% "ammonite-vi" % "2.X")

@


repl.frontEnd() match {
  case ammoniteFrontEnd: ammonite.repl.AmmoniteFrontEnd => {
    com.github.chengpohi.VIMode(repl)
    println("VI Mode Enabled")
  }
  case _ =>
}
```


https://github.com/chengpohi/ammonite-vi/blob/master/README.md
