### ISSUE TITLE
java.lang.NoClassDefFoundError: ammonite/compiler/iface/Parser

### ISSUE THREAD

**Issue by RichardWarfield** [chengpohi/ammonite-vi#3]
I'm getting this when I follow the instructions with scala 2.13 and Ammonite 2.3.8:

```
java.lang.NoClassDefFoundError: ammonite/compiler/iface/Parser
  ammonite.predef.predef_2$.<clinit>(predef.sc:8)
java.lang.ClassNotFoundException: ammonite.compiler.iface.Parser
  java.net.URLClassLoader.findClass(URLClassLoader.java:435)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
  java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  ammonite.predef.predef_2$.<clinit>(predef.sc:8)
```

**Comment by chengpohi** [comment]
Hi @RichardWarfield , Thanks your feedback, This is caused you are installing **amm** for **Scala 2.12** 

https://ammonite.io/#Ammonite-REPL

![image](https://user-images.githubusercontent.com/5118048/118386998-1f136080-b64e-11eb-8317-e552a75fa1df.png)

But for now this plugin only available for ammonite with Scala 2.13, so if you want to use this plugin, maybe you can try to reinstall ammonite with **Scala 2.13** by:

`$ sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.3.8/2.13-2.3.8-65-0f0d597f) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm`



![image](https://user-images.githubusercontent.com/5118048/118387061-947f3100-b64e-11eb-8ab3-2924e445db31.png)

**Comment by RichardWarfield** [comment]
Thanks a lot; upgrading `amm` seems to get it running. 

vim motions seem to only be partially working though; I can use '0' to get to the start of the line but 'f'/'F' don't seem to work as expected for example.

**Comment by chengpohi** [comment]
Yes, it's for now only support common commands.
